services:
  db:
    image: postgres:16
    container_name: lyricists-lexicon-db
    environment:
      POSTGRES_USER: puthyrathy
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lyricists_lexicon
    ports:
      - "5433:5432"
    volumes:
      - lyricists_lexicon_data:/var/lib/postgresql/data

volumes:
  lyricists_lexicon_data:
